### ISSUE TITLE
Custom element

### ISSUE THREAD

**Issue by changbenny** [LingForCC/ringcentral-js-widget#10]
There are some popular libraries which have some concepts really similar to us.
http://riotjs.com/
http://vuejs.org/

Both of them introduce custom elements. I am thinking about the possibility to include in our widget and trying to implement this feature in another branch.

**Comment by LingForCC** [comment]
vuejs is more or less the same as what we are doing for now. The only difference is that they already implement the data-binding mechanism while we need to manipulate data in actions or before/afterUpdate method explicitly.

**Comment by changbenny** [comment]
Now the custom elements is supported without the ability to be customized by users.
Also had the same problems like https://github.com/LingForCC/ringcentral-js-widget/issues/12 when trying to insert nested templates.

**Comment by changbenny** [comment]
Finished by https://github.com/LingForCC/ringcentral-js-widget/commit/9c739bae87e65831c18c490234ea98b54b3d9f73.
