### ISSUE TITLE
Handler is called before widget is fully constructed

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/ringcentral-js-widget#13]
Since we could not control the time handler is called, there are chances that the handler is called before the widget is fully constructed. It seems that we need to bind the handler after widget is fully constructed.

**Comment by changbenny** [comment]
Do you encounter similar problems in real use cases? Currently it seems that the problems is impossible to happen, because actions that trigger handlers is all async and widgets construction is sync which must happen before async actions.

**Comment by LingForCC** [comment]
Bind methods after the dom is created. Something as follows:

![2016-03-07 13_13_06- component js - ringcentral-js-widget - visual studio code](https://cloud.githubusercontent.com/assets/5373202/13561304/61f650d4-e466-11e5-8bc3-6877170908c7.png)
