### ISSUE TITLE
Add a default method in actions to be executed right after widget is mounted

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/ringcentral-js-widget#14]
Now all action methods are called based on a specific user input. It seems that we may need a action method to execute business logic right after widget is mounted. And this action should be called right after widget is mounted. It doesn't need any user input.

**Comment by LingForCC** [comment]
Add default `mount` action as follows:

![2016-03-07 13_16_46- component js - ringcentral-js-widget - visual studio code](https://cloud.githubusercontent.com/assets/5373202/13561486/71f137e0-e468-11e5-93d2-b4a5dc021793.png)

**Comment by changbenny** [comment]
Now widgets have 'render' and 'init' action
