### ISSUE TITLE
Could not fetch template in embedded widget

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/ringcentral-js-widget#5]
The template url used in embedded widget may depend on the path of parent template.

![image](https://cloud.githubusercontent.com/assets/5373202/13547043/fe23921c-e2fb-11e5-830c-de80073a669e.png)

**Comment by changbenny** [comment]
Unfortunately, even after combine scripts and template, we still need a path to the combined file.
[The way Polymer do is to limit file structure.](https://www.polymer-project.org/1.0/docs/start/reusableelements.html#html-imports-and-dependency-management)
For now I think that might be the best solution.

**Comment by LingForCC** [comment]
It seems this is what we could do for now. Let's do it.
