### ISSUE TITLE
template is fetched everytime a new widget is created

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/ringcentral-js-widget#6]
The same template files are fetched several times. Is it possible to provide a way to cache the template file, or maybe do a deep copy of existed widget to eliminate template loading?

![image](https://cloud.githubusercontent.com/assets/5373202/13547045/1802e96c-e2fc-11e5-80ef-0cd29887980d.png)

**Comment by changbenny** [comment]
It's cached by browser already, I am wondering currently does it affect performance?

**Comment by LingForCC** [comment]
It seems that it doesn't affect the performance. Let's leave it as what it is for now.
