### ISSUE TITLE
Find a solution for easy localization

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/ringcentral-js-widget#7]

**Comment by changbenny** [comment]
I found some slim libraries for localization:
https://github.com/eligrey/l10n.js/
https://github.com/l20n/l20n.js
https://github.com/fnando/i18n-js

We should take a look of existed localization process and determine which one is the most suitable.

**Comment by LingForCC** [comment]
I prefer the first one since it is the only one I could understand what is going on. :)

**Comment by LingForCC** [comment]
Move this issue to JIRA
